//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TActivity
    {
        public System.Guid Guid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid BusinessGuid { get; set; }
        public System.Guid CategoryGuid { get; set; }
        public string Title { get; set; }
        public string Images { get; set; }
        public System.DateTime BeginTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string UserAccount { get; set; }
        public int Status { get; set; }
        public int ReadCount { get; set; }
        public int ApplCount { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Detail { get; set; }
    }
}
