//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TArticle
    {
        public System.Guid Guid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid CategoryGuid { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> ChainStoreGuid { get; set; }
        public Nullable<System.Guid> BusinessGuid { get; set; }
        public string Souce { get; set; }
        public string author { get; set; }
        public int Sort { get; set; }
        public System.Guid UserGuid { get; set; }
        public bool IsManager { get; set; }
        public string SmallImg { get; set; }
        public int Status { get; set; }
        public string Target { get; set; }
        public string Level { get; set; }
        public string Describle { get; set; }
        public string Content { get; set; }
        public int Click { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
