//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBusiness
    {
        public System.Guid Guid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public string BusinessName { get; set; }
        public System.Guid AgentsGuid { get; set; }
        public int StoreCount { get; set; }
        public Nullable<bool> IsSystemBusiness { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public string Contact { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> DueTime { get; set; }
        public int ProvinceId { get; set; }
        public int CityID { get; set; }
        public int DistrictId { get; set; }
        public string Address { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Memo { get; set; }
        public Nullable<System.Guid> IndustryGuid { get; set; }
    }
}
