//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TChainStoreSmsSendNote
    {
        public System.Guid Guid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid BusinessGuid { get; set; }
        public System.Guid ChainStoreGuid { get; set; }
        public string Mobiles { get; set; }
        public string SmsContent { get; set; }
        public int SmsCount { get; set; }
        public string SendChanelKeyName { get; set; }
        public System.DateTime SendTime { get; set; }
        public int Status { get; set; }
        public string UserAccount { get; set; }
        public string Memo { get; set; }
    }
}
