//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TComment
    {
        public System.Guid Guid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid ObjectGuid { get; set; }
        public Nullable<System.Guid> ParentGuid { get; set; }
        public Nullable<System.Guid> MemberGuid { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public string Content { get; set; }
        public string Images { get; set; }
        public int StartLevel { get; set; }
        public int SupportCount { get; set; }
        public int OppositionCount { get; set; }
        public System.DateTime SubmitTime { get; set; }
    }
}
