//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCoupon
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> OperatorGuid { get; set; }
        public string Title { get; set; }
        public decimal Value { get; set; }
        public decimal UseValueLimit { get; set; }
        public int TotalCount { get; set; }
        public int SigleReceiveCount { get; set; }
        public int Status { get; set; }
        public int ValidityType { get; set; }
        public Nullable<int> ValidityDay { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int ParticipateStoreCount { get; set; }
        public int MemberReceiveCount { get; set; }
        public int MemberUseCount { get; set; }
        public string Image { get; set; }
        public string Introduce { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
