//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGift
    {
        public System.Guid Guid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid BusinessGuid { get; set; }
        public string Name { get; set; }
        public System.Guid GiftCategoryGuid { get; set; }
        public int SingleLimit { get; set; }
        public decimal Point { get; set; }
        public int Status { get; set; }
        public string Image { get; set; }
        public string Memo { get; set; }
        public string ExchangeType { get; set; }
        public string ExchangeNotes { get; set; }
        public string ExchangeAddress { get; set; }
        public string Description { get; set; }
        public int StockCount { get; set; }
        public int Sort { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int ExchangeCount { get; set; }
    }
}
