//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGoodsProperty
    {
        public System.Guid Guid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid GoodsCategoryGuid { get; set; }
        public string DataType { get; set; }
        public string Name { get; set; }
        public bool Searchable { get; set; }
        public string ValueName { get; set; }
        public string DefaultValue { get; set; }
        public string Options { get; set; }
        public string Remark { get; set; }
    }
}
