//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TImage
    {
        public System.Guid Guid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid BusinessGuid { get; set; }
        public System.Guid ChainStoreGuid { get; set; }
        public System.Guid ObjectGuid { get; set; }
        public int Type { get; set; }
        public string Url { get; set; }
        public int Sort { get; set; }
        public System.DateTime UploadTime { get; set; }
        public Nullable<bool> IsDefult { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Size { get; set; }
    }
}
