//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMemberCoupon
    {
        public System.Guid Guid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid MemberGuid { get; set; }
        public System.Guid CouponGuid { get; set; }
        public string CouponCode { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime SendTime { get; set; }
        public string SendAssociateBillNumber { get; set; }
        public bool IsLocked { get; set; }
        public bool IsUsed { get; set; }
        public string UsedAssociateBillNumber { get; set; }
        public Nullable<System.Guid> UsedChainStoreGuid { get; set; }
        public Nullable<System.DateTime> UsedTime { get; set; }
        public int Type { get; set; }
    }
}
