//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMemberConsumeNote
    {
        public System.Guid Guid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid ChainStoreGuid { get; set; }
        public Nullable<System.Guid> MemberGuid { get; set; }
        public int Type { get; set; }
        public string BillNumber { get; set; }
        public decimal Point { get; set; }
        public decimal ShouldAmount { get; set; }
        public decimal TotalPaid { get; set; }
        public decimal MoneyPaid { get; set; }
        public decimal ValuePaid { get; set; }
        public decimal CardPaid { get; set; }
        public decimal PointPaid { get; set; }
        public decimal CouponPaid { get; set; }
        public decimal ThirdPaid { get; set; }
        public decimal AliPaid { get; set; }
        public string CouponCode { get; set; }
        public decimal OtherPaid { get; set; }
        public decimal CutAmount { get; set; }
        public string UserAccount { get; set; }
        public System.DateTime OperateTime { get; set; }
        public string Memo { get; set; }
    }
}
