//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMember
    {
        public System.Guid Guid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid BusinessGuid { get; set; }
        public System.Guid ChainStoreGuid { get; set; }
        public string CardID { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string PassWord { get; set; }
        public string HeadImg { get; set; }
        public System.Guid CategoryGuid { get; set; }
        public int Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Profession { get; set; }
        public int ProvinceId { get; set; }
        public int CityId { get; set; }
        public int DistrictId { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> RecommendMemberGuid { get; set; }
        public decimal AvailablePoint { get; set; }
        public decimal TotalPoint { get; set; }
        public decimal AvailableValue { get; set; }
        public decimal TotalValue { get; set; }
        public int TotalConsumeCount { get; set; }
        public Nullable<System.DateTime> LastConsumeTime { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime RegTime { get; set; }
        public Nullable<int> RegSource { get; set; }
        public string OpenID { get; set; }
        public string Memo { get; set; }
    }
}
