//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRushOrderItem
    {
        public System.Guid Guid { get; set; }
        public System.Guid OperatorGuid { get; set; }
        public System.Guid RushOrderGuid { get; set; }
        public string OrderCode { get; set; }
        public bool IsUsed { get; set; }
        public Nullable<System.Guid> UsedChainStore { get; set; }
        public Nullable<System.DateTime> UsedTime { get; set; }
        public string UserAccount { get; set; }
    }
}
